---
title: "Clustering Graph (only) of Projection Results" 
author: "Lucas Ma"
---

To begin, load relevant packages to be used for analysis.

```{r loading-packages}
library(dplyr)
library(cluster)
library(tidyverse)
library(factoextra)
library(mclust)
library(stringr)
```

```{r read-csv}

df = read.csv("../Projection/data/projectionResultWithMetaData_G1_VA.csv")

head(df)

df_va <- df |>
  rename(
    "Filename" = `File.Name`,
    "P1" = `Projection..1`,
    "P2" = `Projection..2`,
    "P3" = `Projection..3`,
    "Title" = `Manuscript.Title`,
    "Year" = `Publication.Year`
  ) |>
  filter(P1 * P2 * P3 != 0)

```

**K-means Clustering**

```{r k-calc}

set.seed(27708) # For reproducibility

# Standardization
df_k <- df_va |>
  mutate(
    P1_scaled = scale(P1),
    P2_scaled = scale(P2),
    P3_scaled = scale(P3)
  ) |>
  select(Filename, P1_scaled, P2_scaled, P3_scaled)

# Function to determine the optimal number of clusters using the elbow method
find_optimal_clusters <- function(data) {
  if (is.vector(data)) {
    data <- matrix(data, ncol = 1)
  }
  wss <- (nrow(data) - 1) * sum(apply(data, 2, var))
  for (i in 2:15) {
    wss[i] <- sum(kmeans(data, centers = i)$withinss)
  }
  return(wss)
}

# Determine the number of clusters for P1, P2, and P3
wss_P1 <- find_optimal_clusters(df_k$P1_scaled)
wss_P2 <- find_optimal_clusters(df_k$P2_scaled)
wss_P3 <- find_optimal_clusters(df_k$P3_scaled)

# Plot the elbow method for each column
par(mfrow = c(1, 3))
plot(1:15, wss_P1, type = "b", xlab = "Number of Clusters", ylab = "Within groups sum of squares", main = "P1")
plot(1:15, wss_P2, type = "b", xlab = "Number of Clusters", ylab = "Within groups sum of squares", main = "P2")
plot(1:15, wss_P3, type = "b", xlab = "Number of Clusters", ylab = "Within groups sum of squares", main = "P3")
par(mfrow = c(1, 1))

# If anyone were to change the number of clusters for the three clusterings, please change it here:
k_1 <- 3
k_2 <- 3
k_3 <- 4

kmeans_P1 <- kmeans(matrix(df_k$P1_scaled, ncol = 1), centers = k_1, nstart = 25)
kmeans_P2 <- kmeans(matrix(df_k$P2_scaled, ncol = 1), centers = k_2, nstart = 25)
kmeans_P3 <- kmeans(matrix(df_k$P3_scaled, ncol = 1), centers = k_3, nstart = 25)

# Add the cluster assignments to the original data frame
df_clustered_k <- df_k |> 
  mutate(cluster_P1 = kmeans_P1$cluster,
         cluster_P2 = kmeans_P2$cluster,
         cluster_P3 = kmeans_P3$cluster)
```

```{r examine-cluster}
# Compute silhouette values
sil <- silhouette(kmeans_P1$cluster, dist(df_va$P1))

# Print silhouette summary
summary(sil)

# Visualize silhouette plot
fviz_silhouette(sil)
```

The following chunk is shared by all types of clustering for generating visualization.

```{r k-visual}

clustered <- df_clustered_k

merged_df <- df_va |>
  left_join(clustered, by = "Filename") 

merged_df <- merged_df |>
  mutate(
    cluster_P1 = as.character(cluster_P1),
    cluster_P2 = as.character(cluster_P2),
    cluster_P3 = as.character(cluster_P3)
  ) |>
  select(Filename, P1, P2, P3, Title, Author, Year, cluster_P1, cluster_P2, cluster_P3)


# Filter the dataset for the specified filenames
lines_df <- merged_df |> filter(Filename %in% c("A73849", "A19313", "A14803"))


# Below is the first projection

merged_df |>
  ggplot(aes(x = P1, color = cluster_P1)) +  
  geom_density() +
  geom_jitter(aes(y = 0), width = 0, height = 0.1, size = 0.5) + 
  theme_minimal() +
  labs(title = "One-Dimensional Scatterplot",
       x = "P_civility",
       y = "") +
  theme(axis.title.y = element_blank(),  
        axis.text.y = element_blank(),   
        axis.ticks.y = element_blank())

# Below is the second projection

merged_df |>
  ggplot(aes(x = P2, color = cluster_P2)) +  
  geom_density() +
  geom_jitter(aes(y = 0), width = 0, height = 0.1, size = 0.5) + 
  geom_vline(data = lines_df, aes(xintercept = P2), color = "blue", linetype = "dotted", size = 0.5) +
  annotate("text", x = lines_df$P2[lines_df$Filename == "A73849"], y = 1.5, label = "Donne", vjust = 1, color = "blue3") +
  annotate("text", x = lines_df$P2[lines_df$Filename == "A19313"], y = 1.25, label = "Copland", vjust = 1, color = "blue3") +
  annotate("text", x = lines_df$P2[lines_df$Filename == "A14803"], y = 1, label = "Waterhouse", vjust = 1, color = "blue3") +
  theme_minimal() +
  labs(title = "One-Dimensional Scatterplot",
       x = "P_salvation",
       y = "") +
  theme(axis.title.y = element_blank(),  
        axis.text.y = element_blank(),   
        axis.ticks.y = element_blank()) 

# Below is the third projection

merged_df |>
  ggplot(aes(x = P3, color = cluster_P3)) +  
  geom_density() +
  geom_jitter(aes(y = 0), width = 0, height = 0.2, size = 0.5) + 
  geom_vline(data = lines_df, aes(xintercept = P3), color = "blue", linetype = "dotted", size = 0.5) +
  annotate("text", x = lines_df$P3[lines_df$Filename == "A73849"], y = 1.5, label = "Donne", vjust = 1, color = "blue3") +
  annotate("text", x = lines_df$P3[lines_df$Filename == "A19313"], y = 1.25, label = "Copland", vjust = 1, color = "blue3") +
  annotate("text", x = lines_df$P3[lines_df$Filename == "A14803"], y = 1, label = "Waterhouse", vjust = 1, color = "blue3") +
  theme_minimal() +
  labs(title = "One-Dimensional Scatterplot",
       x = "P_deprive",
       y = "") +
  theme(axis.title.y = element_blank(),  
        axis.text.y = element_blank(),   
        axis.ticks.y = element_blank())

merged_df |>
  select(Author, Year, Filename, cluster_P1, cluster_P2, cluster_P3, P1, P2, P3) |>
  filter(str_detect(Author, "Waterhouse"))
  #filter(P1<0.2413)
```

Below is an improved visualization of the clustering of projection.

```{r better-visual-p1}

annotations <- lines_df |>
  mutate(label = case_when(
    Filename == "A73849" ~ "J. Donne",
    Filename == "A19313" ~ "P. Copland",
    Filename == "A14803" ~ "E. Waterhouse"
  ),
  x_pos = case_when(
    Filename == "A73849" ~ P1 - 0.02,
    Filename == "A19313" ~ P1 + 0.08,
    Filename == "A14803" ~ P1 + 0.08
  ),
  y_pos = case_when(
    Filename == "A73849" ~ 1.3,
    Filename == "A19313" ~ 0.7,
    Filename == "A14803" ~ 1
  ))

merged_df$cluster_P1 <- factor(merged_df$cluster_P1, levels = c(1, 2, 3))

# Define custom labels and colors for the clusters
custom_labels <- c("1" = "More Religious-driven", "2" = "Relatively Neutral", "3" = "Very Financial-driven")
custom_colors <- c("1" = "#66c2a5", "2" = "#fc8d62", "3" = "#8da0cb")

annotated_points <- merged_df %>% filter(Filename %in% c("A73849", "A19313", "A14803"))
remaining_points <- merged_df %>% filter(!Filename %in% c("A73849", "A19313", "A14803"))

glimpse(lines_df)

merged_df |>
  filter(str_detect(Filename, "A14803"))

merged_df |>
  ggplot(aes(x = P1, color = factor(cluster_P1))) +
  geom_density(aes(fill = factor(cluster_P1)), alpha = 0.05) +  
  geom_jitter(
    data = remaining_points, 
    aes(x = P1, y = 0, color = factor(cluster_P1), alpha = 0.15), 
    width = 0, 
    height = 0.1, 
    size = 1.5
  ) +
  geom_jitter(
    data = annotated_points, 
    aes(x = P1, y = 0, color = factor(cluster_P1), alpha = 1), 
    width = 0, 
    height = 0.1, 
    size = 1.5
  )+
  geom_vline(
    xintercept = 0, 
    linetype = "dashed", 
    color = "red3", 
    show.legend = FALSE,
    size = 0.7
  ) +
  geom_vline(
    data = lines_df, 
    aes(xintercept = P1, color = factor(cluster_P1)), 
    linetype = "dotted", 
    size = 0.6, 
    show.legend = FALSE
  ) +
  geom_text(
    data = annotations, 
    aes(x = x_pos, y = y_pos, label = label, color = factor(cluster_P1)), 
    vjust = 1, 
    show.legend = FALSE,
    family = "Times New Roman",
    fontface = "bold",
    angle = -90
  ) +  
  annotate(
    "text", x = -0.25, y = Inf, 
    label = "Absolute\n Neutrality", 
    vjust = 1, color = "red3",
    family = "Times New Roman",
    fontface = "bold"
  ) +
  scale_color_manual(values = custom_colors, labels = custom_labels, name = "Clusters") +  
  scale_fill_manual(values = custom_colors, labels = custom_labels, name = "Clusters") +  
  scale_alpha_identity() +  
  scale_x_continuous(limits = c(-0.3, 3.2)) +
  theme_minimal(base_size = 12) +  
  labs(
    title = 'Distribution of Connotations of "Virginia" \n on Money-Christ Dichotomy',
    x = 'Note: the more rightward, the more monetary is the connotation of "Virginia"',
    y = ""
    ) +
  theme(
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.x = element_blank(),
    legend.position = "top",  
    legend.title = element_blank(), 
    legend.text = element_text(
      size = 10, family = "Times New Roman"
      ),
    panel.grid.major = element_blank(),  
    panel.grid.minor = element_blank(),  
    plot.title = element_text(
      size = 18, hjust = 0.5, margin = margin(b = 20), family = "Times New Roman",
      face = "bold"
      ),
    text = element_text(family = "Times New Roman")
  )
```

```{r better-p2}
annotations <- lines_df |>
  mutate(label = case_when(
    Filename == "A73849" ~ "J. Donne",
    Filename == "A19313" ~ "P. Copland",
    Filename == "A14803" ~ "E. Waterhouse"
  ),
  x_pos = case_when(
    Filename == "A73849" ~ P2 - 0.02,
    Filename == "A19313" ~ P2 + 0.08,
    Filename == "A14803" ~ P2 + 0.08
  ),
  y_pos = case_when(
    Filename == "A73849" ~ 1.3,
    Filename == "A19313" ~ 1.3,
    Filename == "A14803" ~ 1.3
  ))

merged_df$cluster_P2 <- factor(merged_df$cluster_P2, levels = c(1, 2, 3))

# Define custom labels and colors for the clusters
custom_labels <- c("1" = "Dark", "2" = "Relatively Neutral", "3" = "Bright")
custom_colors <- c("1" = "#66c2a5", "2" = "#fc8d62", "3" = "#8da0cb")

annotated_points <- merged_df %>% filter(Filename %in% c("A73849", "A19313", "A14803"))
remaining_points <- merged_df %>% filter(!Filename %in% c("A73849", "A19313", "A14803"))

glimpse(lines_df)


merged_df |>
  ggplot(aes(x = P2, color = factor(cluster_P2))) +
  geom_density(aes(fill = factor(cluster_P2)), alpha = 0.05) +  
  geom_jitter(
    data = remaining_points, 
    aes(x = P2, y = 0, color = factor(cluster_P2), alpha = 0.15), 
    width = 0, 
    height = 0.1, 
    size = 1.5
  ) +
  geom_jitter(
    data = annotated_points, 
    aes(x = P2, y = 0, color = factor(cluster_P2), alpha = 1), 
    width = 0, 
    height = 0.1, 
    size = 1.5
  )+
  geom_vline(
    xintercept = 0, 
    linetype = "dashed", 
    color = "red3", 
    show.legend = FALSE,
    size = 0.7
  ) +
  geom_vline(
    data = lines_df, 
    aes(xintercept = P2, color = factor(cluster_P2)), 
    linetype = "dotted", 
    size = 0.6, 
    show.legend = FALSE
  ) +
  geom_text(
    data = annotations, 
    aes(x = x_pos, y = y_pos, label = label, color = factor(cluster_P2)), 
    vjust = 1, 
    show.legend = FALSE,
    family = "Times New Roman",
    fontface = "bold",
    angle = -90
  ) +  
  annotate(
    "text", x = -0.25, y = Inf, 
    label = "Absolute\n Neutrality", 
    vjust = 1, color = "red3",
    family = "Times New Roman",
    fontface = "bold"
  ) +
  scale_color_manual(values = custom_colors, labels = custom_labels, name = "Clusters") +  
  scale_fill_manual(values = custom_colors, labels = custom_labels, name = "Clusters") +  
  scale_alpha_identity() +  
  #scale_x_continuous(limits = c(-0.3, 3.2)) +
  theme_minimal(base_size = 12) +  
  labs(
    title = 'Distribution of Connotations of "Virginia" \n on Light-Darkness Dichotomy',
    x = 'Note: the more rightward, the more bright is the connotation of "Virginia"',
    y = ""
    ) +
  theme(
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.x = element_blank(),
    legend.position = "top",  
    legend.title = element_blank(), 
    legend.text = element_text(
      size = 10, family = "Times New Roman"
      ),
    panel.grid.major = element_blank(),  
    panel.grid.minor = element_blank(),  
    plot.title = element_text(
      size = 18, hjust = 0.5, margin = margin(b = 20), family = "Times New Roman",
      face = "bold"
      ),
    text = element_text(family = "Times New Roman")
  )
```

```{r better-p3}
annotations <- lines_df |>
  mutate(label = case_when(
    Filename == "A73849" ~ "J. Donne",
    Filename == "A19313" ~ "P. Copland",
    Filename == "A14803" ~ "E. Waterhouse"
  ),
  x_pos = case_when(
    Filename == "A73849" ~ P1 - 0.02,
    Filename == "A19313" ~ P1 + 0.08,
    Filename == "A14803" ~ P1 + 0.08
  ),
  y_pos = case_when(
    Filename == "A73849" ~ 1.3,
    Filename == "A19313" ~ 0.7,
    Filename == "A14803" ~ 1
  ))

merged_df$cluster_P1 <- factor(merged_df$cluster_P1, levels = c(1, 2, 3))

# Define custom labels and colors for the clusters
custom_labels <- c("1" = "More Religious-driven", "2" = "Relatively Neutral", "3" = "Very Financial-driven")
custom_colors <- c("1" = "#66c2a5", "2" = "#fc8d62", "3" = "#8da0cb")

annotated_points <- merged_df %>% filter(Filename %in% c("A73849", "A19313", "A14803"))
remaining_points <- merged_df %>% filter(!Filename %in% c("A73849", "A19313", "A14803"))

glimpse(lines_df)

merged_df |>
  filter(str_detect(Filename, "A14803"))

merged_df |>
  ggplot(aes(x = P1, color = factor(cluster_P1))) +
  geom_density(aes(fill = factor(cluster_P1)), alpha = 0.05) +  
  geom_jitter(
    data = remaining_points, 
    aes(x = P1, y = 0, color = factor(cluster_P1), alpha = 0.15), 
    width = 0, 
    height = 0.1, 
    size = 1.5
  ) +
  geom_jitter(
    data = annotated_points, 
    aes(x = P1, y = 0, color = factor(cluster_P1), alpha = 1), 
    width = 0, 
    height = 0.1, 
    size = 1.5
  )+
  geom_vline(
    xintercept = 0, 
    linetype = "dashed", 
    color = "red3", 
    show.legend = FALSE,
    size = 0.7
  ) +
  geom_vline(
    data = lines_df, 
    aes(xintercept = P1, color = factor(cluster_P1)), 
    linetype = "dotted", 
    size = 0.6, 
    show.legend = FALSE
  ) +
  geom_text(
    data = annotations, 
    aes(x = x_pos, y = y_pos, label = label, color = factor(cluster_P1)), 
    vjust = 1, 
    show.legend = FALSE,
    family = "Times New Roman",
    fontface = "bold",
    angle = -90
  ) +  
  annotate(
    "text", x = -0.25, y = Inf, 
    label = "Absolute\n Neutrality", 
    vjust = 1, color = "red3",
    family = "Times New Roman",
    fontface = "bold"
  ) +
  scale_color_manual(values = custom_colors, labels = custom_labels, name = "Clusters") +  
  scale_fill_manual(values = custom_colors, labels = custom_labels, name = "Clusters") +  
  scale_alpha_identity() +  
  #scale_x_continuous(limits = c(-0.3, 3.2)) +
  theme_minimal(base_size = 12) +  
  labs(
    title = 'Distribution of Connotations of "Virginia" \n on Money-Christ Dichotomy',
    x = 'Note: the more rightward, the more monetary is the connotation of "Virginia"',
    y = ""
    ) +
  theme(
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.x = element_blank(),
    legend.position = "top",  
    legend.title = element_blank(), 
    legend.text = element_text(
      size = 10, family = "Times New Roman"
      ),
    panel.grid.major = element_blank(),  
    panel.grid.minor = element_blank(),  
    plot.title = element_text(
      size = 18, hjust = 0.5, margin = margin(b = 20), family = "Times New Roman",
      face = "bold"
      ),
    text = element_text(family = "Times New Roman")
  )
```

The next chunk is a time-series analysis that attempts to track the use of words and its changes over time.

```{r time-series}

head(merged_df)

process_year <- function(year) {
  # Remove square brackets
  year <- str_replace_all(year, "\\[|\\]", "")
  
  # Split by comma if there are multiple years
  years <- str_split(year, ",\\s*")[[1]]
  # Convert to numeric and take the minimum if there are multiple years
  if (length(years) > 1) {
    year <- min(as.numeric(years))
  }
  return(as.character(year))
}

custom_labels_line <- c("1" = "More Religious-driven", "2" = "Monetary-inclined", "3" = "Very Financial-driven")
custom_colors_line <- c("1" = "#66c2a5", "2" = "#fc8d62", "3" = "#8da0cb")


cy_df <- merged_df |>
  mutate(Year = as.numeric(sapply(Year, process_year))) |>
  filter(Year < 1626 & Year >= 1606) |>
  mutate(Year_Interval = cut(Year, breaks = seq(1606, 1627, by = 5), right = FALSE, labels = seq(1606, 1622, by = 5)))

percentage_p1 <- cy_df |>
  group_by(Year_Interval) |>
  mutate(total_works = n()) |>
  group_by(Year_Interval, cluster_P1) |>
  summarise(count = n(), total_works = first(total_works)) |>
  mutate(percentage = (count / total_works) * 100) |>
  ungroup()

percentage_interval <- percentage_p1 |>
  mutate(new_x = case_when(
    Year_Interval == "1606" ~ "1606 - 1610",
    Year_Interval == "1611" ~ "1611 - 1615",
    Year_Interval == "1616" ~ "1616 - 1620",
    Year_Interval == "1621" ~ "1621 - 1625"
  ))

ggplot(percentage_interval, aes(x = Year_Interval, y = percentage, color = as.factor(cluster_P1), group = cluster_P1)) +
  geom_line(size = 0.8) +
  geom_point(size = 1.5) +
  geom_text(
    aes(
      label = sprintf("%.1f%%", percentage)
      ),
    vjust = -0.75, hjust = 0.5,
    size = 3,
    family = "Times New Roman",
    show.legend = FALSE,
    fontface = "bold"
    ) +
  scale_color_manual(values = custom_colors_line, labels = custom_labels_line, name = "Legend: ") +  
  labs(title = 'Attitudes about "Virginia" Changes over Time \n (5Y Average)',
       x = "Year Interval",
       y = "Percentage") +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1)), limits = c(0, NA)) +  
  theme_minimal(base_size = 15) +
  theme(
    plot.title = element_text(
      size = 20, family = "Times New Roman", face = "bold", 
      margin = margin(b = 20),
      hjust = 0.5
      ),
    axis.title = element_text(size = 14, family = "Times New Roman"),
    axis.text = element_text(size = 12, family = "Times New Roman"),
    axis.text.x = element_text(angle = 0, hjust = 0.5),
    legend.title = element_text(size = 10, family = "Times New Roman"),
    legend.text = element_text(size = 10, family = "Times New Roman"),
    legend.position = "top",
    panel.grid.major = element_line(color = "grey80", size = 0.25),
    panel.grid.minor = element_blank()
  )


ggplot(percentage_p1, aes(x = Year_Interval, y = percentage, color = as.factor(cluster_P1), group = cluster_P1)) +
  geom_line(size = 1) +
  geom_point() +
  labs(title = "Percentage of Works in Each Cluster Over Time (5-Year Intervals)",
       x = "Year Interval",
       y = "Percentage",
       color = "Cluster") +
  scale_fill_manual(values = c("1" = "blue", "2" = "green", "3" = "red"),
                    labels = c("1" = "Cluster 1", "2" = "Cluster 2", "3" = "Cluster 3")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 0, hjust = 1))


```

```{r obsolete-charts}

ggplot(percentage_p1, aes(x = Year_Interval, y = percentage, fill = as.factor(cluster_P1))) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Percentage of Works in Each Cluster Over 5-Year Intervals",
       x = "Year Interval",
       y = "Percentage",
       fill = "Cluster") +
  scale_fill_manual(values = c("1" = "blue", "2" = "green", "3" = "red"),
                    labels = c("1" = "Cluster 1", "2" = "Cluster 2", "3" = "Cluster 3")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


ggplot(percentage_p1, aes(x = Year_Interval, y = percentage, fill = as.factor(cluster_P1))) +
  geom_bar(stat = "identity") +
  labs(title = "Percentage of Works in Each Cluster Over 5-Year Intervals",
       x = "Year Interval",
       y = "Percentage",
       fill = "Cluster") +
  scale_fill_manual(values = c("1" = "blue", "2" = "green", "3" = "red"),
                    labels = c("1" = "Cluster 1", "2" = "Cluster 2", "3" = "Cluster 3")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```
