---
title: "Clustering Graph (only) of Projection Results" 
author: "Lucas Ma"
---

To begin, load relevant packages to be used for analysis.

```{r loading-packages}
library(dplyr)
library(cluster)
library(tidyverse)
library(factoextra)
library(mclust)
library(stringr)
library(ggiraph)
```

```{r read-csv}

df = read.csv("../Projection/data/projectionResultWithMetaData_G1_VA.csv")

df_va <- df |>
  rename(
    "Filename" = `File.Name`,
    "P1" = `Projection..1`,
    "P2" = `Projection..2`,
    "P3" = `Projection..3`,
    "Title" = `Manuscript.Title`,
    "Year" = `Publication.Year`
  ) |>
  filter(P1 * P2 * P3 != 0)

```

**K-means Clustering**

```{r k-calc}

set.seed(27708) # For reproducibility

# Standardization
df_k <- df_va |>
  mutate(
    P1_scaled = scale(P1),
    P2_scaled = scale(P2),
    P3_scaled = scale(P3)
  ) |>
  select(Filename, P1_scaled, P2_scaled, P3_scaled)


# If anyone were to change the number of clusters for the three clusterings, please change it here:
k_1 <- 3
k_2 <- 3
k_3 <- 4

kmeans_P1 <- kmeans(matrix(df_k$P1_scaled, ncol = 1), centers = k_1, nstart = 25)
kmeans_P2 <- kmeans(matrix(df_k$P2_scaled, ncol = 1), centers = k_2, nstart = 25)
kmeans_P3 <- kmeans(matrix(df_k$P3_scaled, ncol = 1), centers = k_3, nstart = 25)

# Add the cluster assignments to the original data frame
df_clustered_k <- df_k |> 
  mutate(cluster_P1 = kmeans_P1$cluster,
         cluster_P2 = kmeans_P2$cluster,
         cluster_P3 = kmeans_P3$cluster)
```

The following chunk is shared by all types of clustering for generating visualization.

```{r k-visual}

clustered <- df_clustered_k

merged_df <- df_va |>
  left_join(clustered, by = "Filename") 

merged_df <- merged_df |>
  mutate(
    cluster_P1 = as.character(cluster_P1),
    cluster_P2 = as.character(cluster_P2),
    cluster_P3 = as.character(cluster_P3)
  ) |>
  select(Filename, P1, P2, P3, Title, Author, Year, cluster_P1, cluster_P2, cluster_P3)


# Filter the dataset for the specified filenames
lines_df <- merged_df |> filter(Filename %in% c("A73849", "A19313", "A14803"))

```

Below is an improved visualization of the clustering of projection.

```{r}
annotations <- lines_df |>
  mutate(label = case_when(
    Filename == "A73849" ~ "J. Donne",
    Filename == "A19313" ~ "P. Copland",
    Filename == "A14803" ~ "E. Waterhouse"
  ),
  x_pos = case_when(
    Filename == "A73849" ~ P1 - 0.02,
    Filename == "A19313" ~ P1 + 0.08,
    Filename == "A14803" ~ P1 + 0.08
  ),
  y_pos = case_when(
    Filename == "A73849" ~ 1.3,
    Filename == "A19313" ~ 0.7,
    Filename == "A14803" ~ 1
  ))

merged_df$cluster_P1 <- factor(merged_df$cluster_P1, levels = c(1, 2, 3))

# Define custom labels and colors for the clusters
custom_labels <- c("1" = "More Religious-driven", "2" = "Relatively Neutral", "3" = "Very Financial-driven")
custom_colors <- c("1" = "#66c2a5", "2" = "#fc8d62", "3" = "#8da0cb")

annotated_points <- merged_df %>% filter(Filename %in% c("A73849", "A19313", "A14803"))
remaining_points <- merged_df %>% filter(!Filename %in% c("A73849", "A19313", "A14803"))

plot <- ggplot() +
  geom_density(data = merged_df, aes(x = P1, color = factor(cluster_P1), fill = factor(cluster_P1)), alpha = 0.05) +  
  geom_jitter_interactive(
    data = remaining_points, 
    aes(x = P1, y = 0, color = factor(cluster_P1), alpha = 0.15, tooltip = paste("Author:", Author, "<br>Filename:", Filename)), 
    width = 0, 
    height = 0.1, 
    size = 1.5
  ) +
  geom_jitter_interactive(
    data = annotated_points, 
    aes(x = P1, y = 0, color = factor(cluster_P1), alpha = 1, tooltip = paste("Author:", Author, "<br>Filename:", Filename)), 
    width = 0, 
    height = 0.1, 
    size = 1.5
  ) +
  geom_vline(
    xintercept = 0, 
    linetype = "dashed", 
    color = "red3", 
    show.legend = FALSE,
    size = 0.7
  ) +
  geom_vline(
    data = lines_df, 
    aes(xintercept = P1, color = factor(cluster_P1)), 
    linetype = "dotted", 
    size = 0.6, 
    show.legend = FALSE
  ) +
  geom_text_interactive(
    data = annotations, 
    aes(x = x_pos, y = y_pos, label = label, color = factor(cluster_P1), tooltip = label), 
    vjust = 1, 
    show.legend = FALSE,
    family = "Times New Roman",
    fontface = "bold",
    angle = -90
  ) +  
  annotate(
    "text", x = -0.25, y = Inf, 
    label = "Absolute\n Neutrality", 
    vjust = 1, color = "red3",
    family = "Times New Roman",
    fontface = "bold"
  ) +
  scale_color_manual(values = custom_colors, labels = custom_labels, name = "Clusters") +  
  scale_fill_manual(values = custom_colors, labels = custom_labels, name = "Clusters") +  
  scale_alpha_identity() +  
  scale_x_continuous(limits = c(-0.3, 3.2)) +
  theme_minimal(base_size = 12) +  
  labs(
    title = 'Distribution of Connotations of "Virginia" \n on Money-Christ Dichotomy',
    x = 'Note: the more rightward, the more monetary is the connotation of "Virginia"',
    y = ""
  ) +
  theme(
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.x = element_blank(),
    legend.position = "top",  
    legend.title = element_blank(), 
    legend.text = element_text(
      size = 10, family = "Times New Roman"
    ),
    panel.grid.major = element_blank(),  
    panel.grid.minor = element_blank(),  
    plot.title = element_text(
      size = 18, hjust = 0.5, margin = margin(b = 20), family = "Times New Roman",
      face = "bold"
    ),
    text = element_text(family = "Times New Roman")
  )

ggiraph(code = {print(plot)}, width_svg = 7, height_svg = 5)

```
